var car = 'GMC';
console.log("Is car == 'GMC'? I Predict True.");
console.log(car == 'GMC');
var my_Name = 'Asad';
console.log("My Name Is == 'Asad'? I Predict True.");
console.log(my_Name == 'Asad');
var my_F_Name = 'Saleem';
console.log("My Father Name Is == 'Saleem'? I Predict True.");
console.log(my_F_Name == 'Saleem');
var my_City_Name = 'Hyderabad';
console.log("My City Name Is == 'Karachi'? I Predict False.");
console.log(my_City_Name == 'Karachi');
var my_Country_Name = 'Pakistan';
console.log("My Country Name Is == 'Pakistan'? I Predict True.");
console.log(my_Country_Name == 'Pakistan');
var fav_Game = 'FootBall';
console.log("My Favourite Game Is == 'Cricket'? I Predict False.");
console.log(fav_Game == 'Cricket');
var fav_Hobby = 'Coding';
console.log("My Favourite Hobby Is == 'Gaming'? I Predict False.");
console.log(fav_Hobby == 'Gaming');
var school_Name = 'GBHS';
console.log("My School Name Is == 'FGBS'? I Predict False.");
console.log(school_Name == 'FGBS');
var my_Age = 18;
console.log("My Age Is == 18? I Predict True.");
console.log(my_Age == 18);
var fav_color = 'Black';
console.log("My Favourite Color Is == 'Black'? I Predict True.");
console.log(fav_color == 'Black');
