var likeVisit = ["Paris", "NewYork", "London", "Saudia", "Dubai"];
console.log(likeVisit);
var ac = likeVisit.concat();
var bc = ac;
bc.sort();
console.log(bc);
console.log(likeVisit);
var cd = likeVisit.concat();
var ef = cd;
ef.sort().reverse();
console.log(ef);
console.log(likeVisit);
likeVisit.reverse();
console.log(likeVisit);
likeVisit.reverse();
console.log(likeVisit);
likeVisit.sort();
console.log(likeVisit);
likeVisit.sort().reverse();
console.log(likeVisit);
